# Generated by Django 5.1.2 on 2024-10-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_id', models.IntegerField(unique=True)),
                ('IBAN', models.CharField(max_length=34, unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('sign', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=25, unique=True)),
                ('admin_permission', models.BooleanField(default=False)),
                ('banker_permission', models.BooleanField(default=False)),
                ('client_permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('date', models.DateField()),
                ('bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.cardtype')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.currency'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.role')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.card')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.currency')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.transactiontype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.user')),
            ],
        ),
        migrations.CreateModel(
            name='CardApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.card')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.cardtype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.user')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.user'),
        ),
        migrations.CreateModel(
            name='BankAccountApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('bank_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.currency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.user')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.user'),
        ),
    ]
