# Generated by Django 5.1.2 on 2024-10-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
