# Generated by Django 5.1.2 on 2024-10-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_user_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=90),
        ),
    ]
