# Generated by Django 5.1.2 on 2024-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_user_is_authenticated_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
