# Generated by Django 5.1.2 on 2024-10-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_remove_user_is_authenticated_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default='2024-10-13 12:15:45', null=True),
        ),
    ]
