# Generated by Django 5.1.2 on 2024-10-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccountapplication',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='bank_account_id',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cardapplication',
            old_name='bank_account_id',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='cardapplication',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardapplication',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='bank_account_id',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
