# Generated by Django 5.1.2 on 2024-10-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_rename_user_id_bankaccountapplication_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='cardApplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.cardapplication'),
        ),
    ]
