# Generated by Django 5.1.2 on 2024-10-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_bankaccount_cardapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='cardApplication',
        ),
        migrations.RemoveField(
            model_name='bankaccountapplication',
            name='bank_account_id',
        ),
        migrations.RemoveField(
            model_name='cardapplication',
            name='card',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bankApplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccountapplication'),
        ),
        migrations.AddField(
            model_name='card',
            name='cardApplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.cardapplication'),
        ),
    ]
