# Generated by Django 5.1.2 on 2024-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_remove_bankaccount_cardapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cardapplication',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
