# Generated by Django 5.1.2 on 2024-10-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_applicationstatus_alter_cardapplication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountapplication',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankaccountapplication',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.applicationstatus'),
        ),
        migrations.AlterField(
            model_name='cardapplication',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.applicationstatus'),
        ),
    ]
