# Generated by Django 5.1.2 on 2024-10-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_alter_bankaccountapplication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
